name: CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: 'zulu'
          java-version: '17'
          check-latest: true

      - name: Test on Ubuntu
        run: ./gradlew assemble check --no-build-cache --no-daemon --stacktrace

  gradle-wrapper-validation:
    name: "Validate the Gradle Wrapper"
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: gradle/actions/wrapper-validation@6cec5d49d4d6d4bb982fbed7047db31ea6d38f11 # v3

  all-checks:
    if: always()
    runs-on: ubuntu-latest
    needs:
      - gradle-wrapper-validation
      - test-ubuntu

    steps:
      - name: require that all other jobs have passed
        uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: publish-snapshot
          jobs: ${{ toJSON(needs) }}